apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    app: db
  ports:
  - port: {{ .Values.db.service.port }}
    targetPort: 5432
  type: {{ .Values.db.service.type }}
